"""
Generic multi-expert agent workflow domain models.

These tables keep the new research-oriented agent system decoupled from the
existing report-generation pipeline while still reusing the shared task table
for lifecycle and auditability.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, List, Optional

from sqlalchemy import Column, DateTime, Float, ForeignKey, Index, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import BaseModel, utc_now


class AgentWorkflowRun(BaseModel):
    """Top-level multi-expert workflow execution."""

    __tablename__ = "agent_runs"

    task_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("tasks.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        comment="Owning task ID",
    )
    mode: Mapped[str] = mapped_column(String(40), nullable=False, default="research", comment="Workflow mode")
    output_format: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        default="evidence_report",
        comment="Requested output format",
    )
    prompt: Mapped[str] = mapped_column(Text, nullable=False, comment="Original user prompt")
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="pending",
        comment="Current workflow status",
    )
    risk_level: Mapped[str] = mapped_column(String(20), nullable=False, default="medium", comment="Risk level")
    country_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("countries.id", ondelete="SET NULL"),
        nullable=True,
        comment="Optional country scope",
    )
    search_scope: Mapped[str] = mapped_column(
        String(80),
        nullable=False,
        default="web+db+memory",
        comment="Search scope",
    )
    memory_scope: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        default="project",
        comment="Memory scope",
    )
    allowed_actions = Column(JSON, nullable=False, default=list, comment="Allow-list of internal actions")
    plan_json = Column(JSON, nullable=False, default=list, comment="Serialized plan nodes")
    summary: Mapped[Optional[str]] = mapped_column(Text, comment="Final summary")
    findings = Column(JSON, nullable=False, default=list, comment="Structured findings")
    citations = Column(JSON, nullable=False, default=list, comment="Structured citations")
    artifacts = Column(JSON, nullable=False, default=list, comment="Artifacts generated by the workflow")
    open_questions = Column(JSON, nullable=False, default=list, comment="Open questions or gaps")
    actions_taken = Column(JSON, nullable=False, default=list, comment="Executed internal actions")
    result_json = Column(JSON, nullable=False, default=dict, comment="Final serialized result")
    budget_tokens_total: Mapped[Optional[int]] = mapped_column(Integer, comment="Total token budget")
    budget_tokens_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Tokens used")
    replan_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Number of replans")
    search_round_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Search rounds")
    review_round_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Review rounds")
    step_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Completed step count")
    error_message: Mapped[Optional[str]] = mapped_column(Text, comment="Workflow error message")
    metadata_ = Column("metadata", JSON, nullable=False, default=dict, comment="Additional metadata")
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), comment="Workflow start time")
    ended_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), comment="Workflow end time")

    task = relationship("Task")
    steps: Mapped[List["AgentWorkflowStep"]] = relationship(
        "AgentWorkflowStep",
        back_populates="run",
        cascade="all, delete-orphan",
        order_by="AgentWorkflowStep.step_order.asc()",
    )
    evidence_items: Mapped[List["AgentWorkflowEvidence"]] = relationship(
        "AgentWorkflowEvidence",
        back_populates="run",
        cascade="all, delete-orphan",
        order_by="AgentWorkflowEvidence.created_at.asc()",
    )
    conversations: Mapped[List["AgentWorkflowConversation"]] = relationship(
        "AgentWorkflowConversation",
        back_populates="run",
        cascade="all, delete-orphan",
        order_by="AgentWorkflowConversation.timestamp.asc()",
    )
    memories: Mapped[List["AgentWorkflowMemory"]] = relationship(
        "AgentWorkflowMemory",
        back_populates="run",
        cascade="all, delete-orphan",
        order_by="AgentWorkflowMemory.created_at.asc()",
    )

    __table_args__ = (
        Index("idx_agent_runs_task", "task_id"),
        Index("idx_agent_runs_status", "status"),
        Index("idx_agent_runs_country", "country_id"),
        Index("idx_agent_runs_created", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<AgentWorkflowRun(id={self.id}, task_id={self.task_id}, status='{self.status}')>"


class AgentWorkflowStep(BaseModel):
    """Individual step execution within a workflow run."""

    __tablename__ = "agent_steps"

    run_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("agent_runs.id", ondelete="CASCADE"),
        nullable=False,
        comment="Parent agent run",
    )
    step_uuid: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        default=lambda: str(uuid.uuid4()),
        comment="Step UUID",
    )
    step_key: Mapped[str] = mapped_column(String(120), nullable=False, comment="Stable plan node key")
    step_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Step order")
    step_type: Mapped[str] = mapped_column(String(40), nullable=False, comment="Node type")
    step_name: Mapped[str] = mapped_column(String(200), nullable=False, comment="Human-readable name")
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="pending",
        comment="Step status",
    )
    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=0, comment="Attempt count")
    input_summary: Mapped[Optional[str]] = mapped_column(Text, comment="Compact input summary")
    output_summary: Mapped[Optional[str]] = mapped_column(Text, comment="Compact output summary")
    input_payload = Column(JSON, nullable=False, default=dict, comment="Structured input payload")
    output_payload = Column(JSON, nullable=False, default=dict, comment="Structured output payload")
    prompt: Mapped[Optional[str]] = mapped_column(Text, comment="Prompt used for the step")
    system_prompt: Mapped[Optional[str]] = mapped_column(Text, comment="System prompt used for the step")
    response: Mapped[Optional[str]] = mapped_column(Text, comment="Raw model response")
    model: Mapped[Optional[str]] = mapped_column(String(120), comment="Model used")
    provider: Mapped[Optional[str]] = mapped_column(String(120), comment="Provider used")
    tokens = Column(JSON, nullable=False, default=dict, comment="Token usage")
    duration: Mapped[Optional[float]] = mapped_column(Float, comment="Step duration in seconds")
    error_message: Mapped[Optional[str]] = mapped_column(Text, comment="Error message if step failed")
    metadata_ = Column("metadata", JSON, nullable=False, default=dict, comment="Additional metadata")
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), comment="Step start time")
    ended_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), comment="Step end time")

    run = relationship("AgentWorkflowRun", back_populates="steps")
    evidence_items: Mapped[List["AgentWorkflowEvidence"]] = relationship(
        "AgentWorkflowEvidence",
        back_populates="step",
        cascade="all, delete-orphan",
        order_by="AgentWorkflowEvidence.created_at.asc()",
    )
    conversations: Mapped[List["AgentWorkflowConversation"]] = relationship(
        "AgentWorkflowConversation",
        back_populates="step",
        cascade="all, delete-orphan",
        order_by="AgentWorkflowConversation.timestamp.asc()",
    )

    __table_args__ = (
        Index("idx_agent_steps_run", "run_id"),
        Index("idx_agent_steps_step_key", "run_id", "step_key", unique=True),
        Index("idx_agent_steps_status", "status"),
        Index("idx_agent_steps_created", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<AgentWorkflowStep(id={self.id}, step_key='{self.step_key}', status='{self.status}')>"


class AgentWorkflowEvidence(BaseModel):
    """Evidence captured from web, database, memory, or internal actions."""

    __tablename__ = "agent_evidence"

    run_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("agent_runs.id", ondelete="CASCADE"),
        nullable=False,
        comment="Parent agent run",
    )
    step_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("agent_steps.id", ondelete="SET NULL"),
        nullable=True,
        comment="Originating step",
    )
    evidence_uuid: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        default=lambda: str(uuid.uuid4()),
        comment="Evidence UUID",
    )
    evidence_type: Mapped[str] = mapped_column(String(30), nullable=False, comment="web/db/memory/action")
    source_type: Mapped[str] = mapped_column(String(50), nullable=False, comment="Source type")
    source_name: Mapped[Optional[str]] = mapped_column(String(200), comment="Source name")
    title: Mapped[Optional[str]] = mapped_column(Text, comment="Evidence title")
    url: Mapped[Optional[str]] = mapped_column(Text, comment="Source URL")
    resolved_url: Mapped[Optional[str]] = mapped_column(Text, comment="Final resolved URL")
    content_snippet: Mapped[Optional[str]] = mapped_column(Text, comment="Short evidence snippet")
    content_hash: Mapped[str] = mapped_column(String(128), nullable=False, comment="Deduplication hash")
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.5, comment="Confidence score")
    weight: Mapped[float] = mapped_column(Float, nullable=False, default=1.0, comment="Relative weight")
    metadata_ = Column("metadata", JSON, nullable=False, default=dict, comment="Additional metadata")

    run = relationship("AgentWorkflowRun", back_populates="evidence_items")
    step = relationship("AgentWorkflowStep", back_populates="evidence_items")

    __table_args__ = (
        Index("idx_agent_evidence_run", "run_id"),
        Index("idx_agent_evidence_step", "step_id"),
        Index("idx_agent_evidence_hash", "run_id", "content_hash", unique=True),
        Index("idx_agent_evidence_created", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<AgentWorkflowEvidence(id={self.id}, source_type='{self.source_type}')>"


class AgentWorkflowConversation(BaseModel):
    """Detailed model interaction log for workflow agents."""

    __tablename__ = "agent_conversations"

    run_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("agent_runs.id", ondelete="CASCADE"),
        nullable=False,
        comment="Parent agent run",
    )
    step_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("agent_steps.id", ondelete="SET NULL"),
        nullable=True,
        comment="Originating step",
    )
    conversation_uuid: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        default=lambda: str(uuid.uuid4()),
        comment="Conversation UUID",
    )
    agent_role: Mapped[str] = mapped_column(String(50), nullable=False, comment="Agent role")
    phase: Mapped[Optional[str]] = mapped_column(String(50), comment="Workflow phase")
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utc_now, nullable=False
    )
    prompt: Mapped[Optional[str]] = mapped_column(Text, comment="Prompt sent to model")
    system_prompt: Mapped[Optional[str]] = mapped_column(Text, comment="System prompt")
    response: Mapped[Optional[str]] = mapped_column(Text, comment="Model response")
    model: Mapped[Optional[str]] = mapped_column(String(120), comment="Model used")
    provider: Mapped[Optional[str]] = mapped_column(String(120), comment="Provider used")
    tokens = Column(JSON, nullable=False, default=dict, comment="Token usage")
    duration: Mapped[Optional[float]] = mapped_column(Float, comment="Call duration")
    temperature: Mapped[Optional[float]] = mapped_column(Float, comment="Sampling temperature")
    metadata_ = Column("metadata", JSON, nullable=False, default=dict, comment="Additional metadata")

    run = relationship("AgentWorkflowRun", back_populates="conversations")
    step = relationship("AgentWorkflowStep", back_populates="conversations")

    __table_args__ = (
        Index("idx_agent_conversations_run", "run_id"),
        Index("idx_agent_conversations_step", "step_id"),
        Index("idx_agent_conversations_created", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<AgentWorkflowConversation(id={self.id}, agent_role='{self.agent_role}')>"


class AgentWorkflowMemory(BaseModel):
    """Persisted memory unit for long-term retrieval and semantic search."""

    __tablename__ = "agent_memories"

    run_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("agent_runs.id", ondelete="CASCADE"),
        nullable=True,
        comment="Optional parent run",
    )
    task_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("tasks.id", ondelete="SET NULL"),
        nullable=True,
        comment="Optional owning task",
    )
    memory_uuid: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        default=lambda: str(uuid.uuid4()),
        comment="Memory UUID",
    )
    scope: Mapped[str] = mapped_column(String(50), nullable=False, default="project", comment="Memory scope")
    memory_type: Mapped[str] = mapped_column(String(50), nullable=False, comment="Memory type")
    content: Mapped[Optional[str]] = mapped_column(Text, comment="Full content")
    summary: Mapped[Optional[str]] = mapped_column(Text, comment="Short summary")
    source_type: Mapped[Optional[str]] = mapped_column(String(50), comment="Source type")
    source_ref: Mapped[Optional[str]] = mapped_column(String(500), comment="Source reference")
    content_hash: Mapped[str] = mapped_column(String(128), nullable=False, comment="Deduplication hash")
    embedding = Column(JSON, nullable=False, default=list, comment="Stored embedding vector")
    collection_name: Mapped[Optional[str]] = mapped_column(String(100), comment="Qdrant collection name")
    qdrant_point_id: Mapped[Optional[str]] = mapped_column(String(120), comment="Qdrant point ID")
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="active", comment="Memory status")
    metadata_ = Column("metadata", JSON, nullable=False, default=dict, comment="Additional metadata")

    run = relationship("AgentWorkflowRun", back_populates="memories")

    __table_args__ = (
        Index("idx_agent_memories_run", "run_id"),
        Index("idx_agent_memories_task", "task_id"),
        Index("idx_agent_memories_scope", "scope"),
        Index("idx_agent_memories_hash", "content_hash"),
        Index("idx_agent_memories_created", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<AgentWorkflowMemory(id={self.id}, scope='{self.scope}', status='{self.status}')>"
