export const compactResearchArticle = (article: any) => ({
  article_id: article.article_id,
  slug: article.slug,
  title: article.title,
  doi: article.doi,
  journal: article.journal,
  publisher: article.publisher,
  authors: article.authors ?? [],
  study_type: article.study_type,
  published_at: article.published_at,
  open_access_status: article.open_access_status,
  open_access_url: article.open_access_url,
  peer_review_status: article.peer_review_status,
  discovery_score: article.discovery_score,
  diseases: article.diseases ?? [],
  countries: article.countries ?? [],
  topics: article.topics ?? [],
  related_surveillance: article.related_surveillance ?? [],
  pathogens: article.pathogens ?? [],
  pathogen_types: article.pathogen_types ?? [],
  populations: article.populations ?? [],
  source_kind: article.source_kind,
  historical_baseline: article.historical_baseline,
  publication_date_label_en: article.publication_date_label_en,
  publication_date_label_zh: article.publication_date_label_zh,
  why_it_matters_en: article.why_it_matters_en,
  why_it_matters_zh: article.why_it_matters_zh,
});
