/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.types.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 03c08b7c27ca6dda34d4c5b34596ad3d)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	SITUATION_ALERT_QUEUE: Queue;
	ENVIRONMENT: string;
	PUBLIC_BASE_URL: string;
	ALLOWED_ORIGINS: string;
	DEBUG_RETURN_TOKENS: string;
	PENDING_EXPIRY_DAYS: string;
	SUBMISSION_RATE_LIMIT_PER_HOUR: string;
	CONFIRMATION_EMAIL_LIMIT_PER_10_MINUTES: string;
	NOTIFICATION_BATCH_SIZE: string;
	SITUATION_ALERT_BATCH_SIZE: string;
	SITUATION_ALERT_MAX_ATTEMPTS: string;
	SITUATION_ALERT_RETENTION_DAYS: string;
	SITUATION_ALERT_AUTOMATED_POLICY_ENABLED: string;
	SITUATION_PUBLIC_ORIGINS: string;
	SMTP_HOST: string;
	SMTP_PORT: string;
	SMTP_FROM_EMAIL: string;
	SMTP_FROM_NAME: string;
	SMTP_USE_TLS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PUBLIC_BASE_URL" | "ALLOWED_ORIGINS" | "DEBUG_RETURN_TOKENS" | "PENDING_EXPIRY_DAYS" | "SUBMISSION_RATE_LIMIT_PER_HOUR" | "CONFIRMATION_EMAIL_LIMIT_PER_10_MINUTES" | "NOTIFICATION_BATCH_SIZE" | "SITUATION_ALERT_BATCH_SIZE" | "SITUATION_ALERT_MAX_ATTEMPTS" | "SITUATION_ALERT_RETENTION_DAYS" | "SITUATION_ALERT_AUTOMATED_POLICY_ENABLED" | "SITUATION_PUBLIC_ORIGINS" | "SMTP_HOST" | "SMTP_PORT" | "SMTP_FROM_EMAIL" | "SMTP_FROM_NAME" | "SMTP_USE_TLS">> {}
}
