/** Canonical disease names for synchronized locale switching. */
export type DiseaseNameLocale = 'en' | 'zh' | 'fr';

export const DISEASE_NAMES_FR: Record<string, string> = {
  "accident-caused-by-venomous-animals": "Accident causé par des animaux venimeux",
  "acute-encephalitis-excluding-japanese-and-west-nile-encephalitis": "Encéphalite aiguë à l'exclusion de l'encéphalite japonaise et de l'encéphalite du Nil occidental",
  "acute-flaccid-paralysis": "Paralysie flaccide aiguë",
  "acute-hemorrhagic-conjunctivitis": "Conjonctivite hémorragique aiguë",
  "acute-hepatitis-b": "Hépatite B aiguë",
  "acute-hepatitis-c": "Hépatite C aiguë",
  "african-trypanosomiasis": "Trypanosomiase africaine",
  "aids": "SIDA",
  "amebiasis": "Amibiase intestinale",
  "anthrax": "Charbon bactéridien (anthrax)",
  "arboviral-diseases": "Maladies à arbovirus",
  "arenaviral-haemorrhagic-fever": "Fièvre hémorragique arénavirale",
  "aseptic-meningitis": "Méningite aseptique",
  "babesiosis": "Babésiose",
  "bacterial-meningitis": "Méningite bactérienne",
  "barmah-forest-virus-infection": "Infection au virus de la forêt de Barmah",
  "blastomycosis": "Blastomycose",
  "botulism": "Botulisme",
  "brucellosis": "Brucellose",
  "campylobacteriosis": "Campylobactériose",
  "candida-auris-infection": "Infection à Candida auris",
  "carbapenem-resistant-enterobacterales-infection": "Infection à entérobactéries résistantes au carbapénème",
  "carbapenemase-producing-enterobacteriaceae-surveillance": "Surveillance des entérobactéries productrices de carbapénémase",
  "carbapenemase-producing-organisms-surveillance": "Surveillance des organismes producteurs de carbapénémase",
  "cat-scratch-disease": "Fièvre des griffes de chat",
  "chagas-disease": "Maladie de Chagas",
  "chancroid": "Chancre mou",
  "chikungunya": "Chikungunya",
  "child-exposed-to-hiv": "Enfant exposé au VIH",
  "chlamydia-trachomatis-infection": "Infection à Chlamydia trachomatis",
  "chlamydial-pneumonia": "Pneumonie chlamydiale",
  "cholera": "Choléra",
  "chronic-hepatitis-b": "Hépatite chronique B",
  "chronic-hepatitis-c": "Hépatite C chronique",
  "chronic-viral-hepatitis": "Hépatite virale chronique",
  "clonorchiasis": "Clonorchiase",
  "coccidioidomycosis": "Coccidioïdomycose",
  "community-associated-methicillin-resistant-staphylococcus-aureus-infection": "Infection à Staphylococcus aureus résistante à la méthicilline associée à la communauté",
  "complicated-varicella": "Varicelle compliquée",
  "congenital-rubella-syndrome": "Infection au virus d'herpès simplex néonatal",
  "congenital-syphilis": "Infection à Treponema pallidum congénitale",
  "covid-19": "COVID-19",
  "creutzfeldt-jakob-disease": "pseudosclérose spastique",
  "crimean-congo-hemorrhagic-fever": "Fièvre hémorragique de Crimée (virus Congo)",
  "cronobacter-invasive-infection": "Infection invasive à Cronobacter",
  "cryptosporidiosis": "Cryptosporidiose",
  "cyclosporiasis": "Cyclosporose",
  "cysticercosis": "Cysticercose",
  "decompression-sickness": "Accident de décompression",
  "dengue": "Dengue",
  "diphtheria": "Diphtérie",
  "disseminated-cryptococcosis": "Cryptococcose généralisée",
  "domestic-sexual-and-other-violence": "Violence familiale, sexuelle et autre",
  "donovanosis": "Donovanose",
  "dysentery": "Dysenterie",
  "eastern-equine-encephalitis": "Encéphalite équine de l'Est",
  "ebola": "Maladie à virus Ebola",
  "echinococcosis": "Échinococcose",
  "ehrlichiosis-and-anaplasmosis": "Ehrlichiose et anaplasmose",
  "endemic-typhus-fever": "Infection à Rickettsia typhi",
  "enterovirus-71-infection": "Infection par l'entérovirus 71",
  "enterovirus-infection-with-severe-complications": "Infection à entérovirus avec complications graves",
  "epidemic-keratoconjunctivitis": "Kératoconjonctivite épidémique",
  "epidemic-typhus-fever": "Typhus transmis par pou (épidémique)",
  "erythema-infectiosum-(fifth-disease)": "5e maladie",
  "esbl-ampc-producing-organism-surveillance": "Surveillance des organismes producteurs de BLSE/AmpC",
  "escherichia-coli-enteritis,-all-reported-pathotypes": "Entérite à Escherichia coli, tous les pathotypes signalés",
  "exanthematous-diseases": "Maladies éruptives",
  "exogenous-poisoning": "Intoxication exogène",
  "filariasis": "Filariose",
  "flavivirus-infection-(unspecified)": "Infection à flavivirus (non précisée)",
  "foodborne-disease-outbreak": "Éclosion de maladie d’origine alimentaire",
  "gastroenteritis": "Gastro-entérite",
  "giardiasis": "Giardiase",
  "glanders": "Morve",
  "gonococcal-infection": "Blennorragie gonococcique",
  "gonorrhea": "Gonorrhée",
  "group-a-streptococcal-pharyngitis": "• Pharyngite à streptocoque du groupe A",
  "h5n1": "Infection humaine par le virus H5N1",
  "h7n9": "Infection humaine par le virus H7N9",
  "haemolytic-uraemic-syndrome-(hus)": "SHU (Syndrome Hémolytique et Urémique)",
  "haemophilus-influenzae": "Haemophilus influenzae",
  "hand-foot-mouth-disease": "Maladie pieds-mains-bouche",
  "hantavirus-hemorrhagic-fever": "Fièvre hémorragique à hantavirus",
  "hantavirus-infection": "Infection à hantavirus",
  "hantavirus-pulmonary-syndrome": "Syndrome pulmonaire à hantavirus",
  "hantavirus-syndrome": "Syndrome à hantavirus",
  "hemolytic-uremic-syndrome": "Syndrome hémolytique et urémique",
  "hemorrhagic-fever": "Fièvre hémorragique",
  "hendra-virus-infection": "Infection par le virus Hendra",
  "hepatitis-a": "Hépatite A",
  "hepatitis-b": "Hépatite B",
  "hepatitis-c": "Hépatite C",
  "hepatitis-d": "Hépatite D",
  "hepatitis-e": "Hépatite E",
  "herpangina": "Angine pustuleuse",
  "herpes-b-virus-infection": "Infection par le virus de l'herpès B",
  "herpesviral-infections": "Infections à herpèsvirus",
  "hiv-infection": "Infection à VIH",
  "hiv-infection-in-pregnancy-surveillance-event": "Événement de surveillance du VIH pendant la grossesse",
  "human-t-lymphotropic-virus-1-or-2-infection": "Infection par le virus T-lymphotrope humain de type 1 ou 2",
  "infectious-diarrhea": "Diarrhée infectieuse",
  "infectious-mononucleosis": "Mononucléose infectieuse",
  "infectious-syphilis": "Syphilis infectieuse",
  "infectious-syphilis-under-two-years-duration": "Syphilis infectieuse évoluant depuis moins de deux ans",
  "influenza": "Grippe",
  "influenza-associated-mortality": "Mortalité associée à la grippe",
  "invasive-group-a-streptococcal-infection": "• Infection aux streptocoques du groupe A invasif (SGA) :",
  "invasive-pneumococcal-disease": "Infections invasives à pneumocoques",
  "japanese-encephalitis": "Encéphalite japonaise",
  "japanese-spotted-fever": "Fièvre tachetée japonaise",
  "kala-azar": "Leishmaniose viscérale (kala-azar)",
  "kyasanur-forest-disease": "Maladie de la forêt Kyasanur",
  "lassa": "Fièvre de Lassa",
  "legionellosis": "Légionellose",
  "leishmaniasis": "Leishmaniose",
  "leprosy": "Lèpre",
  "leptospirosis": "Leptospirose",
  "listeriosis": "Listériose",
  "lyme-disease": "Maladie de Lyme",
  "lymphogranuloma-venereum": "Lymphogranulome vénérien",
  "lyssavirus-infection-excluding-rabies": "Infection à Lyssavirus à l'exclusion de la rage",
  "malaria": "Paludisme",
  "marburg-virus-disease": "Fièvre hémorragique de Marbourg",
  "measles": "Rougeole",
  "melioidosis": "Infection à Burkholderia pseudomallei",
  "meningitis-(all-reported-etiologies)": "Méningite (toutes les étiologies déclarées)",
  "meningococcal-disease": "Maladie à méningocoques",
  "mers": "Syndrome respiratoire du Moyen-Orient (MERS)",
  "methicillin-resistant-staphylococcus-aureus-(mrsa)-surveillance": "Programme canadien de surveillance des infections nosocomiales",
  "monkeypox": "Variole du singe",
  "multidrug-resistant-acinetobacter-infection": "Infection à Acinetobacter multirésistante",
  "multidrug-resistant-pseudomonas-aeruginosa-infection": "Infection à Pseudomonas aeruginosa multirésistante",
  "multidrug-resistant-tuberculosis": "TB-MR",
  "mumps": "Oreillons",
  "murray-valley-encephalitis-virus-infection": "24. Virus de l'encéphalite de la Murray Valley",
  "mycoplasma-pneumonia": "Pneumopathie à Mycoplasma pneumoniae",
  "neonatal-group-b-streptococcal-disease": "Maladie streptococcique néonatale du groupe B",
  "neonatal-tetanus": "Tétanos néonatal",
  "nipah-virus-infection": "Infection par le virus Nipah",
  "noise-induced-hearing-loss": "Perte auditive due au bruit",
  "non-tuberculous-mycobacterial-infection": "Infection mycobactérienne non tuberculeuse",
  "novel-influenza-a": "Grippe A nouvelle",
  "omsk-hemorrhagic-fever": "Fièvre hémorragique d'Omsk",
  "ophthalmia-neonatorum": "Ophtalmie du nouveau-né",
  "oropouche-virus-disease": "Maladie à virus Oropouche",
  "other-acute-viral-hepatitis": "Autres hépatites virales aiguës",
  "other-fluke-infections": "Autres infections à trématodes",
  "other-parasitologically-confirmed-malaria": "Autre paludisme confirmé par examen parasitologique",
  "other-viral-diseases": "Autres maladies virales",
  "other-viral-haemorrhagic-fevers": "Autres fièvres hémorragiques virales",
  "other-viral-infections-characterized-by-skin-lesions": "Autres infections virales caractérisées par des lésions cutanées",
  "paralytic-shellfish-poisoning": "Intoxication paralysante par les fruits de mer",
  "paratyphoid-fever": "Fièvre paratyphoïde (Lat.: Febris paratyphoidea)",
  "penicillin-non-susceptible-resistant-pneumococcal-surveillance": "Surveillance des pneumocoques non sensibles/résistants à la pénicilline",
  "perinatal-hepatitis-b": "Hépatite B périnatale",
  "perinatal-hepatitis-c": "Hépatite C périnatale",
  "pertussis": "Coqueluche",
  "pharyngoconjunctival-fever": "Fièvre pharyngo-conjonctivale",
  "plague": "Peste",
  "plasmodium-falciparum-malaria": "Paludisme à Plasmodium falciparum",
  "plasmodium-malariae-malaria": "Paludisme à Plasmodium malariae",
  "plasmodium-vivax-malaria": "Paludisme à Plasmodium vivax",
  "pneumoconiosis": "Pneumoconiose",
  "poliomyelitis": "Poliomyélite",
  "powassan-virus-disease": "Maladie à virus Powassan",
  "psittacosis": "Psittacose",
  "q-fever": "Fièvre Q",
  "rabies": "Rage",
  "rabies-post-exposure-prophylaxis": "Prophylaxie post-exposition contre la rage",
  "relapsing-fever": "fièvre récurrente",
  "respiratory-syncytial-virus-infection-(rsv)": "Infection respiratoire par virus syncytial",
  "rheumatic-fever": "Rhumatisme articulaire aigu",
  "rickettsial-disease": "Infections à Rickettsia",
  "rift-valley-fever": "Fièvre de la vallée du Rift",
  "rocky-mountain-spotted-fever": "fièvre pourprée des montagnes rocheuses",
  "roseola-(exanthem-subitum)": "Roseole (exanthème subalterne)",
  "ross-river-virus-infection": "Infection à virus de la rivière Ross",
  "rotavirus-infection": "Infection à rotavirus",
  "rubella": "Rubéole",
  "salmonellosis": "Salmonellose",
  "sars": "SRAS",
  "scarlet-fever": "Scarlatine",
  "schistosomiasis": "Schistosomiase",
  "scrub-typhus": "Typhus des broussailles",
  "serious-work-accident": "Accident du travail grave",
  "severe-complicated-covid-19": "COVID-19 sévère avec complications",
  "severe-complicated-influenza": "Grippe compliquée sévère",
  "severe-invasive-streptococcal-infection": "Infection streptococcique invasive sevère",
  "sfts": "Syndrome de fièvre sévère avec thrombocytopénie",
  "shiga-toxin-producing-escherichia-coli-infection": "E. coli vérotoxique",
  "shigellosis": "Shigellose",
  "smallpox": "Variole",
  "south-american-hemorrhagic-fever": "Fièvre hémorragique américaine",
  "sporotrichosis": "Sporotrichose",
  "spotted-fever-rickettsiosis": "Fièvre tachetée rickettsiose",
  "streptococcal-disease": "Streptococcie",
  "streptococcus-suis": "Infection à Streptococcus suis",
  "syphilis": "Syphilis",
  "syphilis-in-pregnancy": "Syphilis pendant la grossesse",
  "syphilis-over-two-years-or-unspecified-duration": "Syphilis évoluant depuis plus de deux ans ou de durée indéterminée",
  "taeniasis": "Téniase",
  "tetanus": "Tétanos",
  "tick-borne-encephalitis": "Encéphalite à tiques",
  "toxic-shock-syndrome": "Syndrome de choc toxique",
  "toxoplasmosis": "Toxoplasmose",
  "toxoplasmosis-in-pregnancy": "Toxoplasmose pendant la grossesse",
  "trachoma": "Trachome",
  "trichinellosis": "Trichinellose",
  "tuberculosis": "Tuberculose",
  "tularemia": "Tularémie",
  "typhoid-and-paratyphoid-fever": "Fièvre typhoïde et paratyphoïde",
  "typhoid-fever": "Fièvre typhoïde",
  "typhus": "Typhus",
  "unspecified-malaria": "Paludisme sans précision",
  "unspecified-viral-hepatitis": "Hépatite virale sans précision",
  "vancomycin-intermediate-staphylococcus-aureus-infection": "Infection à Staphylococcus aureus intermédiaire à la Vancomycine",
  "vancomycin-resistance": "Résistance à la vancomycine",
  "vancomycin-resistant-staphylococcus-aureus-infection": "Staphylococcus aureus résistant à la vancomycine",
  "varicella": "Varicelle",
  "varicella-zoster-virus-infection-unspecified": "Infection par le virus varicelle-zona non précisée",
  "venezuelan-equine-encephalitis": "encéphalite équine du Venezuela",
  "vibriosis": "Infections à Vibrio",
  "viral-conjunctivitis": "Conjonctivite virale",
  "viral-hemorrhagic-fevers": "Fièvre Virale Hémorragique",
  "viral-hepatitis": "Hépatites virales",
  "viral-infection-of-unspecified-site": "Infection virale de siège non précisé",
  "viral-meningoencephalitis-surveillance": "Surveillance de la méningo-encéphalite virale",
  "west-nile-virus": "Virus du Nil occidental",
  "western-equine-encephalitis": "Encéphalite équine de l'Ouest",
  "work-accident-with-biological-material": "Accident du travail avec matériel biologique",
  "work-related-cancer": "Cancer lié au travail",
  "work-related-dermatosis": "Dermatose liée au travail",
  "work-related-mental-disorder": "Trouble mental lié au travail",
  "work-related-repetitive-strain-injury": "Lésion professionnelle due aux efforts répétitifs",
  "yellow-fever": "Fièvre jaune",
  "yersiniosis": "Yersiniose",
  "zika-virus-disease": "Maladie à virus Zika",
  "zoster": "Zona",
};

export const DISEASE_NAMES_FR_BY_ID: Record<string, string> = {
  "D001": "Peste",
  "D002": "Choléra",
  "D003": "SRAS",
  "D004": "COVID-19",
  "D005": "SIDA",
  "D006": "Hépatites virales",
  "D007": "Hépatite A",
  "D008": "Hépatite B",
  "D009": "Hépatite C",
  "D010": "Hépatite D",
  "D011": "Hépatite E",
  "D013": "Poliomyélite",
  "D014": "Infection humaine par le virus H5N1",
  "D015": "Infection humaine par le virus H7N9",
  "D016": "Grippe A nouvelle",
  "D017": "Rougeole",
  "D018": "Fièvre hémorragique",
  "D019": "Rage",
  "D020": "Encéphalite japonaise",
  "D021": "Dengue",
  "D023": "Charbon bactéridien (anthrax)",
  "D024": "Dysenterie",
  "D025": "Tuberculose",
  "D026": "Fièvre typhoïde et paratyphoïde",
  "D028": "Coqueluche",
  "D029": "Diphtérie",
  "D030": "Tétanos néonatal",
  "D031": "Scarlatine",
  "D032": "Brucellose",
  "D033": "Gonorrhée",
  "D034": "Syphilis",
  "D035": "Leptospirose",
  "D036": "Schistosomiase",
  "D037": "Paludisme",
  "D038": "Grippe",
  "D039": "Oreillons",
  "D040": "Rubéole",
  "D041": "Conjonctivite hémorragique aiguë",
  "D042": "Lèpre",
  "D043": "Typhus",
  "D044": "Leishmaniose viscérale (kala-azar)",
  "D045": "Échinococcose",
  "D046": "Filariose",
  "D047": "Diarrhée infectieuse",
  "D048": "Maladie pieds-mains-bouche",
  "D049": "Syndrome respiratoire du Moyen-Orient (MERS)",
  "D050": "Maladie à virus Ebola",
  "D051": "Maladie à virus Zika",
  "D052": "Chikungunya",
  "D053": "Fièvre de Lassa",
  "D054": "Varicelle",
  "D055": "Clonorchiase",
  "D056": "Infection à Streptococcus suis",
  "D057": "Syndrome de fièvre sévère avec thrombocytopénie",
  "D058": "Typhus des broussailles",
  "D059": "Fièvre jaune",
  "D060": "Fièvre hémorragique arénavirale",
  "D061": "Autres fièvres hémorragiques virales",
  "D062": "Infections à herpèsvirus",
  "D063": "Zona",
  "D064": "Variole",
  "D065": "Variole du singe",
  "D066": "Autres infections virales caractérisées par des lésions cutanées",
  "D068": "Hépatite B aiguë",
  "D069": "Autres hépatites virales aiguës",
  "D070": "Hépatite virale chronique",
  "D071": "Hépatite virale sans précision",
  "D073": "Mononucléose infectieuse",
  "D074": "Conjonctivite virale",
  "D075": "Autres maladies virales",
  "D076": "Infection virale de siège non précisé",
  "D077": "Paludisme à Plasmodium falciparum",
  "D078": "Paludisme à Plasmodium vivax",
  "D079": "Paludisme à Plasmodium malariae",
  "D080": "Autre paludisme confirmé par examen parasitologique",
  "D081": "Paludisme sans précision",
  "D082": "Leishmaniose",
  "D083": "Trypanosomiase africaine",
  "D084": "Maladie de Chagas",
  "D085": "Toxoplasmose",
  "D086": "Autres infections à trématodes",
  "D087": "Téniase",
  "D088": "Cysticercose",
  "D089": "Maladies à arbovirus",
  "D090": "Babésiose",
  "D091": "Botulisme",
  "D092": "Campylobactériose",
  "D093": "Chancre mou",
  "D094": "Infection à Chlamydia trachomatis",
  "D095": "Coccidioïdomycose",
  "D096": "Cryptosporidiose",
  "D097": "Cyclosporose",
  "D098": "Ehrlichiose et anaplasmose",
  "D099": "Giardiase",
  "D100": "Haemophilus influenzae",
  "D101": "Infection à Candida auris",
  "D102": "Infection à hantavirus",
  "D103": "Syndrome hémolytique et urémique",
  "D104": "Mortalité associée à la grippe",
  "D105": "Shigellose",
  "D106": "Infections invasives à pneumocoques",
  "D107": "Légionellose",
  "D108": "Listériose",
  "D109": "Maladie de Lyme",
  "D110": "Maladie à méningocoques",
  "D112": "Psittacose",
  "D113": "Fièvre Q",
  "D114": "Salmonellose",
  "D115": "E. coli vérotoxique",
  "D116": "Infection à Burkholderia pseudomallei",
  "D117": "Infection invasive à Cronobacter",
  "D118": "Fièvre tachetée rickettsiose",
  "D119": "Streptococcie",
  "D120": "Tétanos",
  "D121": "Syndrome de choc toxique",
  "D122": "Trichinellose",
  "D123": "Tularémie",
  "D124": "Fièvre typhoïde",
  "D125": "Résistance à la vancomycine",
  "D126": "Infections à Vibrio",
  "D127": "Fièvre Virale Hémorragique",
  "D128": "Virus du Nil occidental",
  "D129": "Maladie à virus Oropouche",
  "D131": "Infection à Staphylococcus aureus intermédiaire à la Vancomycine",
  "D132": "Staphylococcus aureus résistant à la vancomycine",
  "D133": "Surveillance des organismes producteurs de carbapénémase",
  "D134": "Méningite aseptique",
  "D135": "Méningite bactérienne",
  "D136": "Pneumonie chlamydiale",
  "D137": "Kératoconjonctivite épidémique",
  "D138": "5e maladie",
  "D139": "Angine pustuleuse",
  "D140": "Pneumopathie à Mycoplasma pneumoniae",
  "D141": "Fièvre pharyngo-conjonctivale",
  "D142": "Infection respiratoire par virus syncytial",
  "D143": "Roseole (exanthème subalterne)",
  "D144": "pseudosclérose spastique",
  "D145": "fièvre récurrente",
  "D146": "Cryptococcose généralisée",
  "D147": "Infection au virus de la forêt de Barmah",
  "D148": "Donovanose",
  "D149": "Infection à flavivirus (non précisée)",
  "D150": "Blennorragie gonococcique",
  "D151": "SHU (Syndrome Hémolytique et Urémique)",
  "D152": "24. Virus de l'encéphalite de la Murray Valley",
  "D153": "Infection mycobactérienne non tuberculeuse",
  "D154": "Infection à virus de la rivière Ross",
  "D155": "Yersiniose",
  "D156": "Gastro-entérite",
  "D157": "• Infection aux streptocoques du groupe A invasif (SGA) :",
  "D158": "Rhumatisme articulaire aigu",
  "D159": "Infections à Rickettsia",
  "D161": "Accident de décompression",
  "D162": "Infection à VIH",
  "D163": "Fièvre hémorragique à hantavirus",
  "D164": "Syndrome pulmonaire à hantavirus",
  "D165": "Amibiase intestinale",
  "D166": "TB-MR",
  "D167": "Infection à Treponema pallidum congénitale",
  "D168": "Infection au virus d'herpès simplex néonatal",
  "D169": "Infection à Rickettsia typhi",
  "D170": "Varicelle compliquée",
  "D171": "Infection par le virus de l'herpès B",
  "D172": "Grippe compliquée sévère",
  "D173": "Fièvre de la vallée du Rift",
  "D174": "Fièvre hémorragique de Marbourg",
  "D175": "Infection par le virus Nipah",
  "D177": "Fièvre des griffes de chat",
  "D178": "Paralysie flaccide aiguë",
  "D180": "Infection à entérovirus avec complications graves",
  "D181": "COVID-19 sévère avec complications",
  "D182": "Syndrome à hantavirus",
  "D183": "Typhus transmis par pou (épidémique)",
  "D184": "Accident causé par des animaux venimeux",
  "D185": "Accident du travail avec matériel biologique",
  "D186": "Accident du travail grave",
  "D187": "Prophylaxie post-exposition contre la rage",
  "D188": "Cancer lié au travail",
  "D189": "Dermatose liée au travail",
  "D190": "Sporotrichose",
  "D191": "Intoxication exogène",
  "D192": "Lésion professionnelle due aux efforts répétitifs",
  "D193": "Trouble mental lié au travail",
  "D194": "Perte auditive due au bruit",
  "D195": "Pneumoconiose",
  "D196": "Éclosion de maladie d’origine alimentaire",
  "D197": "Syphilis pendant la grossesse",
  "D198": "Toxoplasmose pendant la grossesse",
  "D199": "Infection à rotavirus",
  "D200": "Trachome",
  "D201": "Maladies éruptives",
  "D202": "Violence familiale, sexuelle et autre",
  "D203": "Fièvre hémorragique de Crimée (virus Congo)",
  "D204": "Fièvre hémorragique américaine",
  "D205": "Encéphalite à tiques",
  "D206": "Infection à Staphylococcus aureus résistante à la méthicilline associée à la communauté",
  "D207": "Infection par l'entérovirus 71",
  "D208": "Hépatite chronique B",
  "D209": "Hépatite B périnatale",
  "D210": "Hépatite C aiguë",
  "D211": "Hépatite C chronique",
  "D212": "Hépatite C périnatale",
  "D213": "Infection par le virus varicelle-zona non précisée",
  "D214": "Infection à Lyssavirus à l'exclusion de la rage",
  "D215": "Infection par le virus Hendra",
  "D216": "Encéphalite aiguë à l'exclusion de l'encéphalite japonaise et de l'encéphalite du Nil occidental",
  "D217": "Maladie de la forêt Kyasanur",
  "D218": "Encéphalite équine de l'Est",
  "D219": "Encéphalite équine de l'Ouest",
  "D220": "encéphalite équine du Venezuela",
  "D221": "Morve",
  "D222": "Fièvre tachetée japonaise",
  "D223": "fièvre pourprée des montagnes rocheuses",
  "D224": "• Pharyngite à streptocoque du groupe A",
  "D225": "Infection streptococcique invasive sevère",
  "D226": "Fièvre hémorragique d'Omsk",
  "D227": "Infection à entérobactéries résistantes au carbapénème",
  "D228": "Infection à Acinetobacter multirésistante",
  "D229": "Infection à Pseudomonas aeruginosa multirésistante",
  "D230": "Enfant exposé au VIH",
  "D231": "Événement de surveillance du VIH pendant la grossesse",
  "D232": "Syphilis infectieuse évoluant depuis moins de deux ans",
  "D233": "Syphilis évoluant depuis plus de deux ans ou de durée indéterminée",
  "D234": "Fièvre paratyphoïde (Lat.: Febris paratyphoidea)",
  "D235": "Méningite (toutes les étiologies déclarées)",
  "D236": "Programme canadien de surveillance des infections nosocomiales",
  "D237": "Surveillance des organismes producteurs de BLSE/AmpC",
  "D238": "Infection par le virus T-lymphotrope humain de type 1 ou 2",
  "D239": "Surveillance des pneumocoques non sensibles/résistants à la pénicilline",
  "D240": "Surveillance de la méningo-encéphalite virale",
  "D241": "Entérite à Escherichia coli, tous les pathotypes signalés",
  "D242": "Lymphogranulome vénérien",
  "D243": "Blastomycose",
  "D244": "Surveillance des entérobactéries productrices de carbapénémase",
  "D245": "Maladie streptococcique néonatale du groupe B",
  "D246": "Ophtalmie du nouveau-né",
  "D247": "Intoxication paralysante par les fruits de mer",
  "D248": "Maladie à virus Powassan",
  "D249": "Syphilis infectieuse",
};

export interface DiseaseNameRecord {
  disease_id?: string | null;
  slug?: string | null;
  name_en?: string | null;
  name_zh?: string | null;
  name_fr?: string | null;
}

export function localizedDiseaseName(record: DiseaseNameRecord, locale: DiseaseNameLocale = 'en'): string {
  const english = record.name_en ?? record.slug ?? '';
  const chinese = record.name_zh ?? english;
  const french = record.name_fr ?? (record.slug ? DISEASE_NAMES_FR[record.slug] : undefined) ?? (record.disease_id ? DISEASE_NAMES_FR_BY_ID[record.disease_id] : undefined);
  // Some compact API payloads identify diseases by D-numbers rather than slugs.
  // Callers can provide a localized name directly when a slug is unavailable.
  if (locale === 'zh') return chinese;
  if (locale === 'fr') return french ?? english;
  return english;
}
