export const canonicalRoutes = [
  "/overview",
  "/overview/events",
  "/operations/sources",
  "/operations/tasks",
  "/operations/schedules",
  "/operations/schedules/ingestion",
  "/operations/runtime",
  "/data/analytics",
  "/data/diseases",
  "/data/quality",
  "/data/explorer",
  "/data/knowledge",
  "/data/mappings",
  "/data/audit",
  "/production/ai",
  "/production/runs",
  "/production/interactions",
  "/production/reports",
  "/production/releases",
  "/production/distribution",
  "/production/campaigns",
  "/settings/integrations",
  "/settings/models",
] as const;
