#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/commit_data_refresh.sh [options]
  scripts/commit_data_refresh.sh [options] -- <refresh command> [args...]

Options:
  -m, --message MESSAGE   Commit message to use.
      --path PATH         Add an extra generated-data path to snapshot.
      --dry-run           Show what would be committed without staging or committing.
  -h, --help              Show this help.

Examples:
  scripts/commit_data_refresh.sh
  scripts/commit_data_refresh.sh -- make site-data
  scripts/commit_data_refresh.sh -- python main.py crawl --country AU --source all --process --save-raw

By default this snapshots only generated data paths:
  astro-site/src/data
  data/current
  data/raw
EOF
}

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$ROOT_DIR" ]]; then
  echo "Not inside a git repository." >&2
  exit 1
fi

cd "$ROOT_DIR"

dry_run=0
commit_message=""
paths=()
refresh_command=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -m|--message)
      if [[ $# -lt 2 ]]; then
        echo "$1 requires a value." >&2
        exit 2
      fi
      commit_message="$2"
      shift 2
      ;;
    --path)
      if [[ $# -lt 2 ]]; then
        echo "$1 requires a value." >&2
        exit 2
      fi
      paths+=("$2")
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --)
      shift
      refresh_command=("$@")
      break
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "${#paths[@]}" -eq 0 ]]; then
  paths=(
    "astro-site/src/data"
    "data/current"
    "data/raw"
  )
fi

if [[ "${#refresh_command[@]}" -gt 0 ]]; then
  echo "Running refresh command: ${refresh_command[*]}"
  "${refresh_command[@]}"
fi

if ! git diff --cached --quiet --; then
  cat >&2 <<'EOF'
There are already staged changes in the index.
Commit or unstage them first so the data snapshot cannot accidentally include unrelated work.
EOF
  exit 1
fi

target_status="$(git status --porcelain=v1 --untracked-files=normal -- "${paths[@]}")"
if [[ -z "$target_status" ]]; then
  echo "No generated data changes found."
  exit 0
fi

echo "Generated data changes:"
printf '%s\n' "$target_status"

if [[ "$dry_run" == "1" ]]; then
  echo
  echo "Dry run only. Nothing was staged or committed."
  exit 0
fi

git add -A -- "${paths[@]}"

if git diff --cached --quiet -- "${paths[@]}"; then
  echo "No committable changes after staging. Some files may be ignored by .gitignore."
  exit 0
fi

if [[ -z "$commit_message" ]]; then
  commit_message="chore(data): snapshot refresh $(date '+%Y-%m-%d %H:%M')"
fi

changed_count="$(git diff --cached --name-only -- "${paths[@]}" | wc -l | tr -d '[:space:]')"
shortstat="$(git diff --cached --shortstat -- "${paths[@]}" || true)"
body="$(
  cat <<EOF
Generated by scripts/commit_data_refresh.sh.

Paths:
$(printf ' - %s\n' "${paths[@]}")

Files changed: ${changed_count}
${shortstat}
EOF
)"

git commit -m "$commit_message" -m "$body"

echo "Created data refresh commit: $(git rev-parse --short HEAD)"
