#!/usr/bin/env python3
"""Import AU national monthly data into disease_records.

Input default:
  data/raw/au/australia_national_data.csv

This importer is designed for AU data generated by location aggregation.
It auto-ensures:
- countries.code=AU
- disease assets + AU local-name mappings
- idempotent upsert into disease_records by (time, disease_id, country_id)
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime, time
from pathlib import Path

from sqlalchemy import text

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.core.country_library import get_country_bootstrap_config, get_country_profile
from src.core.database import get_db
from src.core.db_schema import ensure_country_scope, ensure_country_scope_schema
from src.core.logging import get_logger

logger = get_logger(__name__)

DEFAULT_INPUT = ROOT / "data/raw/au/australia_national_data.csv"
DEFAULT_SOURCE = "Australia NINDSS (location aggregated)"


@dataclass(frozen=True)
class AURow:
    disease: str
    disease_full: str
    report_date: date
    cases: int
    group: str
    incidence: float | None
    population: int | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import AU national monthly CSV into disease_records.",
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Path to AU national CSV")
    parser.add_argument("--source-name", default=DEFAULT_SOURCE, help="data_source value")
    parser.add_argument("--replace-existing", action="store_true", help="Delete existing AU disease_records before import")
    parser.add_argument("--dry-run", action="store_true", help="Parse and prepare, do not write DB")
    return parser.parse_args()


def norm_text(value: object) -> str:
    if value is None:
        return ""
    return " ".join(str(value).replace("\ufeff", "").split()).strip()


def parse_int(value: object) -> int | None:
    txt = norm_text(value)
    if not txt:
        return None
    try:
        return int(float(txt))
    except ValueError:
        return None


def parse_float(value: object) -> float | None:
    txt = norm_text(value)
    if not txt:
        return None
    try:
        return float(txt)
    except ValueError:
        return None


def parse_date_row(row: dict[str, str]) -> date | None:
    date_text = norm_text(row.get("Date"))
    if date_text:
        for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
            try:
                return datetime.strptime(date_text, fmt).date()
            except ValueError:
                pass

    year = parse_int(row.get("Year"))
    month = parse_int(row.get("Month"))
    if year is not None and month is not None and 1 <= month <= 12:
        return date(year, month, 1)

    month_text = norm_text(row.get("Month"))
    if year is not None and month_text:
        for fmt in ("%B", "%b"):
            try:
                parsed = datetime.strptime(month_text, fmt)
                return date(year, parsed.month, 1)
            except ValueError:
                pass

    return None


def slug_text(value: str) -> str:
    lowered = norm_text(value).lower()
    lowered = lowered.replace("-", " ")
    lowered = re.sub(r"[^a-z0-9 ]+", "", lowered)
    return " ".join(lowered.split())


def resolve_disease_code(disease_name: str) -> str:
    slug = slug_text(disease_name)
    if re.fullmatch(r"D\d{3}", disease_name.upper()):
        return disease_name.upper()
    if re.fullmatch(r"D\d{3}", slug.upper()):
        return slug.upper()

    digest = hashlib.sha1(slug.encode("utf-8")).hexdigest()[:10].upper()
    return f"AU_{digest}"


def load_rows(input_file: Path) -> list[AURow]:
    rows: list[AURow] = []
    with input_file.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for src in reader:
            disease = norm_text(src.get("Disease"))
            disease_full = norm_text(src.get("DiseaseFull")) or disease
            report_date = parse_date_row(src)
            cases = parse_int(src.get("Cases"))
            if not disease or report_date is None or cases is None:
                continue

            rows.append(
                AURow(
                    disease=disease,
                    disease_full=disease_full,
                    report_date=report_date,
                    cases=max(0, cases),
                    group=norm_text(src.get("Group")),
                    incidence=parse_float(src.get("Incidence")),
                    population=parse_int(src.get("Population")),
                )
            )

    rows.sort(key=lambda r: (r.report_date, r.disease))
    return rows


async def ensure_country_au(db) -> int:
    await ensure_country_scope_schema(db)

    profile = get_country_profile("AU")
    bootstrap = get_country_bootstrap_config("AU")

    await db.execute(
        text(
            """
            INSERT INTO countries (
                code, name, name_en, name_local, language, timezone,
                data_source_url, data_source_type,
                crawler_config, parser_config, disease_mapping_rules, report_config,
                is_active, metadata, notes, created_at, updated_at
            ) VALUES (
                :code, :name, :name_en, :name_local, :language, :timezone,
                :data_source_url, :data_source_type,
                CAST(:crawler_config AS json), CAST(:parser_config AS json),
                CAST(:disease_mapping_rules AS json), CAST(:report_config AS json),
                true, CAST(:metadata AS json), :notes, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            )
            ON CONFLICT (code) DO UPDATE SET
                name = EXCLUDED.name,
                name_en = EXCLUDED.name_en,
                name_local = EXCLUDED.name_local,
                language = COALESCE(NULLIF(countries.language, ''), EXCLUDED.language),
                timezone = COALESCE(NULLIF(countries.timezone, ''), EXCLUDED.timezone),
                data_source_url = COALESCE(NULLIF(countries.data_source_url, ''), EXCLUDED.data_source_url),
                data_source_type = COALESCE(NULLIF(countries.data_source_type, ''), EXCLUDED.data_source_type),
                updated_at = CURRENT_TIMESTAMP
            """
        ),
        {
            "code": "AU",
            "name": profile.name,
            "name_en": profile.name_en,
            "name_local": profile.name_local,
            "language": profile.language,
            "timezone": profile.timezone,
            "data_source_url": bootstrap.get("data_source_url"),
            "data_source_type": bootstrap.get("data_source_type"),
            "crawler_config": json.dumps(bootstrap.get("crawler_config", {})),
            "parser_config": json.dumps(bootstrap.get("parser_config", {})),
            "disease_mapping_rules": json.dumps(bootstrap.get("disease_mapping_rules", {})),
            "report_config": json.dumps(bootstrap.get("report_config", {})),
            "metadata": json.dumps({"origin": "scripts/import_au_national_history.py"}),
            "notes": bootstrap.get("notes", "Bootstrapped by AU national importer"),
        },
    )

    await ensure_country_scope(
        db,
        scope_code="AU",
        country_code="AU",
        scope_type="canonical",
        language_code="en-au",
        display_name=profile.name,
        is_default=True,
        is_active=True,
        metadata={"origin": "scripts/import_au_national_history.py"},
    )

    result = await db.execute(text("SELECT id FROM countries WHERE code = 'AU'"))
    row = result.fetchone()
    if not row:
        raise RuntimeError("Failed to ensure countries.code=AU")
    return int(row[0])


async def ensure_disease_assets(db, rows: list[AURow]) -> dict[str, int]:
    labels = {r.disease for r in rows}
    code_by_label = {label: resolve_disease_code(label) for label in labels}
    unique_codes = sorted(set(code_by_label.values()))

    for code in unique_codes:
        default_name = next((k for k, v in code_by_label.items() if v == code), code)
        await db.execute(
            text(
                """
                INSERT INTO diseases (
                    name, name_en, category, aliases, keywords, metadata,
                    is_active, created_at, updated_at
                ) VALUES (
                    :name, :name_en, :category, '[]'::json, '[]'::json,
                    CAST(:metadata AS json),
                    true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                )
                ON CONFLICT (name) DO UPDATE SET
                    name_en = COALESCE(NULLIF(diseases.name_en, ''), EXCLUDED.name_en),
                    category = COALESCE(NULLIF(diseases.category, ''), EXCLUDED.category),
                    metadata = EXCLUDED.metadata,
                    updated_at = CURRENT_TIMESTAMP
                """
            ),
            {
                "name": code,
                "name_en": default_name,
                "category": "Notifiable",
                "metadata": json.dumps({"origin": "au_national_auto"}),
            },
        )

    for row in rows:
        disease_code = code_by_label[row.disease]

        mapping_names = {row.disease}
        if row.disease_full and row.disease_full != row.disease:
            mapping_names.add(row.disease_full)

        for local_name in mapping_names:
            await db.execute(
                text(
                    """
                    INSERT INTO disease_mappings (
                        disease_id, country_code, local_name,
                        is_primary, is_alias, priority,
                        usage_count, confidence_score,
                        category, source, metadata, is_active,
                        created_at, updated_at
                    ) VALUES (
                        :disease_id, 'AU', :local_name,
                        :is_primary, :is_alias, :priority,
                        0, 1.0,
                        :category, :source, CAST(:metadata AS json), true,
                        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    )
                    ON CONFLICT (disease_id, country_code, local_name) DO UPDATE SET
                        source = EXCLUDED.source,
                        metadata = EXCLUDED.metadata,
                        updated_at = CURRENT_TIMESTAMP
                    """
                ),
                {
                    "disease_id": disease_code,
                    "local_name": local_name,
                    "is_primary": local_name == row.disease,
                    "is_alias": local_name != row.disease,
                    "priority": 100 if local_name == row.disease else 80,
                    "category": "Notifiable",
                    "source": "AU national monthly import",
                    "metadata": json.dumps({"origin": "scripts/import_au_national_history.py"}),
                },
            )

    result = await db.execute(
        text("SELECT id, name FROM diseases WHERE name = ANY(:codes)"),
        {"codes": unique_codes},
    )
    id_by_code = {row[1]: int(row[0]) for row in result.fetchall()}
    missing = [c for c in unique_codes if c not in id_by_code]
    if missing:
        raise RuntimeError(f"Missing diseases after upsert: {missing[:5]}")

    return {label: id_by_code[code] for label, code in code_by_label.items()}


async def upsert_records(
    db,
    *,
    country_id: int,
    rows: list[AURow],
    disease_id_by_label: dict[str, int],
    source_name: str,
    input_file: Path,
) -> int:
    payload: list[dict[str, object]] = []
    seen: set[tuple[datetime, int, int]] = set()

    for row in rows:
        disease_id = disease_id_by_label.get(row.disease)
        if disease_id is None:
            continue

        dt = datetime.combine(row.report_date, time.min)
        key = (dt, disease_id, country_id)
        if key in seen:
            continue
        seen.add(key)

        metadata_obj = {
            "source_csv": input_file.name,
            "disease": row.disease,
            "disease_full": row.disease_full,
            "group": row.group,
            "population": row.population,
            "incidence": row.incidence,
        }

        raw_obj = {
            "Disease": row.disease,
            "DiseaseFull": row.disease_full,
            "Date": row.report_date.isoformat(),
            "Cases": row.cases,
            "Group": row.group,
            "Population": row.population,
            "Incidence": row.incidence,
        }

        payload.append(
            {
                "time": dt,
                "disease_id": disease_id,
                "country_id": country_id,
                "cases": row.cases,
                "deaths": 0,
                "region": None,
                "data_source": source_name,
                "incidence_rate": row.incidence,
                "metadata": json.dumps(metadata_obj),
                "raw_data": json.dumps(raw_obj),
            }
        )

    if not payload:
        return 0

    await db.execute(
        text(
            """
            INSERT INTO disease_records (
                time, disease_id, country_id, cases, deaths,
                region, data_source, incidence_rate,
                new_cases, new_deaths, recoveries, active_cases, new_recoveries,
                metadata, raw_data
            ) VALUES (
                :time, :disease_id, :country_id, :cases, :deaths,
                :region, :data_source, :incidence_rate,
                0, 0, 0, 0, 0,
                CAST(:metadata AS json), CAST(:raw_data AS json)
            )
            ON CONFLICT (time, disease_id, country_id) DO UPDATE SET
                cases = EXCLUDED.cases,
                deaths = EXCLUDED.deaths,
                region = EXCLUDED.region,
                data_source = EXCLUDED.data_source,
                incidence_rate = EXCLUDED.incidence_rate,
                metadata = EXCLUDED.metadata,
                raw_data = EXCLUDED.raw_data
            """
        ),
        payload,
    )
    return len(payload)


async def run_import(args: argparse.Namespace) -> None:
    if not args.input.exists():
        raise FileNotFoundError(f"Input file not found: {args.input}")

    rows = load_rows(args.input)
    if not rows:
        logger.warning("No AU rows parsed from input, nothing to import.")
        return

    disease_count = len({r.disease for r in rows})
    logger.info(f"Prepared {len(rows):,} AU rows ({disease_count:,} diseases)")

    if args.dry_run:
        logger.info("Dry run enabled: skip database writes.")
        return

    async with get_db() as db:
        country_id = await ensure_country_au(db)

        if args.replace_existing:
            deleted = await db.execute(
                text("DELETE FROM disease_records WHERE country_id = :country_id"),
                {"country_id": country_id},
            )
            logger.info(f"Deleted existing AU disease_records: {deleted.rowcount or 0:,}")

        disease_id_by_label = await ensure_disease_assets(db, rows)
        inserted = await upsert_records(
            db,
            country_id=country_id,
            rows=rows,
            disease_id_by_label=disease_id_by_label,
            source_name=args.source_name,
            input_file=args.input,
        )

        await db.commit()
        logger.info(f"Imported/updated AU disease_records rows: {inserted:,}")


def main() -> None:
    args = parse_args()
    asyncio.run(run_import(args))


if __name__ == "__main__":
    main()
